version: '2'
services:
  firstclient-postgresql:
    image: postgres:11.3
    # volumes:
    #     - ~/volumes/jhipster/firstclient/postgresql/:/var/lib/postgresql/data/
    environment:
      - POSTGRES_USER=firstclient
      - POSTGRES_PASSWORD=
    ports:
      - 5432:5432
